services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: habit
      POSTGRES_PASSWORD: habitpwd
      POSTGRES_DB: habitdb   # <- tolto lo spazio prima dei due punti
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habit -d habitdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    depends_on: 
      db:
        condition: service_healthy
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080   # <- fa ascoltare Kestrel su 8080 dentro il container
      # FORZO la conn string corretta lato runtime (override di qualunque appsettings/secrets)
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=habitdb;Username=habit;Password=habitpwd;SSL Mode=Disable"
    ports:
      - "8082:8080" # host:container
volumes:
  pgdata: {}
