// <auto-generated />
using System;
using MagicalHabitTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicalHabitTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250929193640_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("MagicalHabitTracker.Model.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayofMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Periodicity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetPeriod")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("MagicalHabitTracker.Model.HabitSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HabitId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextDueUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("PreferredLocalTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReminderOffsetsMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SnoozeUntilUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeeklyDaysMask")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HabitId")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("MagicalHabitTracker.Model.Tracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("HabitId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HabitId", "Date")
                        .IsUnique();

                    b.ToTable("HabitTrackers");
                });

            modelBuilder.Entity("MagicalHabitTracker.Model.HabitSchedule", b =>
                {
                    b.HasOne("MagicalHabitTracker.Model.Habit", "Habit")
                        .WithOne("HabitSchedule")
                        .HasForeignKey("MagicalHabitTracker.Model.HabitSchedule", "HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("MagicalHabitTracker.Model.Tracker", b =>
                {
                    b.HasOne("MagicalHabitTracker.Model.Habit", "Habit")
                        .WithMany("Trackers")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("MagicalHabitTracker.Model.Habit", b =>
                {
                    b.Navigation("HabitSchedule");

                    b.Navigation("Trackers");
                });
#pragma warning restore 612, 618
        }
    }
}
